### ISSUE TITLE
Define a Storage-to-Storage "Ingest" action

### ISSUE THREAD

**Issue by jdraines** [jdraines/ragmatic#5]
Being able to retrieve data from one storage source and load it into another will be a key dependency for applications that use data sources like s3 or data warehouses as the long-term source of truth for documents, but require a lower latency source when running RAG actions.

This action would have an expected configuration somewhat like:

```yaml
action: ingest
config:
  storage_source: <ref to storage>
  storage_destination: <ref to destination>
```

A new preset data structure based on remote ingestion can be created in `cli/configuration/presets`, and once well supported by concrete storage classes, can become the default preset.

The reffed sources can accept configuration values that accommodate incremental pipelining if desired. These values can then be overridden in CLI commands via the `-v key=value` format when calling a preset.
